services:
  drupal:
    image: custom-drupal
    # shortcut for current folder and default dockerfile
    build: .
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    ports:
      - '8080:80'
  postgres:
    image: postgres:14
    environment: 
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: